# Form implementation generated from reading ui file 'Dialog_confirm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 230)
        Dialog.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 560, 40))
        self.label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.confirm_button = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(30, 180, 180, 40))
        self.confirm_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 8px;")
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(350, 180, 180, 40))
        self.cancel_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 8px;")
        self.cancel_button.setObjectName("cancel_button")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 500, 130))
        self.label_2.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Подтвердите удаление строки"))
        self.confirm_button.setText(_translate("Dialog", "Подтвердить действие"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.label_2.setText(_translate("Dialog", "1, 3, 65, 23, 45, 123"))
