# Form implementation generated from reading ui file 'Dialog_lineEdit.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 275)
        Dialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 541, 40))
        self.label.setStyleSheet("font: 16pt \"Segoe UI\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.confirm_button = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(30, 220, 200, 40))
        self.confirm_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 8px;")
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(330, 220, 200, 40))
        self.cancel_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 8px;")
        self.cancel_button.setObjectName("cancel_button")
        self.name_lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.name_lineEdit.setGeometry(QtCore.QRect(280, 10, 280, 41))
        self.name_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 8px;\n"
"")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 500, 140))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Введите имя группы:"))
        self.confirm_button.setText(_translate("Dialog", "Создать группу"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.label_2.setText(_translate("Dialog", "1, 3, 65, 23, 45, 123"))
