# Form implementation generated from reading ui file 'exit.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1558, 870)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/psychology_24dp_1C3854_FILL0_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 75 11pt \"Segoe UI\";\n"
"background-color: rgb(245, 245, 245);\n"
"alternate-background-color: rgb(245, 245, 245);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("font: 75 12pt \"Segoe UI\";")
        self.centralwidget.setObjectName("centralwidget")
        self.help_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.help_widget.setGeometry(QtCore.QRect(420, 40, 541, 531))
        self.help_widget.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.help_widget.setObjectName("help_widget")
        self.text_label_3 = QtWidgets.QLabel(parent=self.help_widget)
        self.text_label_3.setGeometry(QtCore.QRect(20, 90, 501, 251))
        self.text_label_3.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";")
        self.text_label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.text_label_3.setObjectName("text_label_3")
        self.label_3 = QtWidgets.QLabel(parent=self.help_widget)
        self.label_3.setGeometry(QtCore.QRect(24, 15, 501, 31))
        self.label_3.setStyleSheet("font: 16pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.help_close_button_3 = QtWidgets.QPushButton(parent=self.help_widget)
        self.help_close_button_3.setGeometry(QtCore.QRect(360, 450, 150, 40))
        self.help_close_button_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.help_close_button_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.help_close_button_3.setObjectName("help_close_button_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1551, 821))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.init_tablename = QtWidgets.QLabel(parent=self.page_1)
        self.init_tablename.setGeometry(QtCore.QRect(25, 20, 270, 45))
        self.init_tablename.setStyleSheet("font: 16pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.init_tablename.setObjectName("init_tablename")
        self.filter_widget = QtWidgets.QWidget(parent=self.page_1)
        self.filter_widget.setGeometry(QtCore.QRect(980, 0, 541, 711))
        self.filter_widget.setAutoFillBackground(False)
        self.filter_widget.setStyleSheet("")
        self.filter_widget.setObjectName("filter_widget")
        self.filter_window_frame = QtWidgets.QFrame(parent=self.filter_widget)
        self.filter_window_frame.setGeometry(QtCore.QRect(20, 69, 501, 551))
        self.filter_window_frame.setStyleSheet("")
        self.filter_window_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filter_window_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.filter_window_frame.setObjectName("filter_window_frame")
        self.filter_reg_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_reg_label.setGeometry(QtCore.QRect(20, 10, 350, 45))
        self.filter_reg_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_reg_label.setLineWidth(0)
        self.filter_reg_label.setObjectName("filter_reg_label")
        self.filter_city_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_city_label.setGeometry(QtCore.QRect(20, 190, 350, 45))
        self.filter_city_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_city_label.setLineWidth(0)
        self.filter_city_label.setObjectName("filter_city_label")
        self.filter_grnti_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_grnti_label.setGeometry(QtCore.QRect(20, 280, 211, 45))
        self.filter_grnti_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_grnti_label.setLineWidth(0)
        self.filter_grnti_label.setObjectName("filter_grnti_label")
        self.filter_keyword_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_keyword_label.setGeometry(QtCore.QRect(20, 370, 350, 45))
        self.filter_keyword_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_keyword_label.setLineWidth(0)
        self.filter_keyword_label.setObjectName("filter_keyword_label")
        self.filter_reg_comboBox = QtWidgets.QComboBox(parent=self.filter_window_frame)
        self.filter_reg_comboBox.setGeometry(QtCore.QRect(20, 50, 461, 45))
        self.filter_reg_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filter_reg_comboBox.setObjectName("filter_reg_comboBox")
        self.filter_grnti_lineEdit = QtWidgets.QLineEdit(parent=self.filter_window_frame)
        self.filter_grnti_lineEdit.setGeometry(QtCore.QRect(20, 320, 211, 45))
        self.filter_grnti_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.filter_grnti_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_grnti_lineEdit.setObjectName("filter_grnti_lineEdit")
        self.filter_keywords_lineEdit = QtWidgets.QLineEdit(parent=self.filter_window_frame)
        self.filter_keywords_lineEdit.setGeometry(QtCore.QRect(20, 410, 461, 45))
        self.filter_keywords_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_keywords_lineEdit.setObjectName("filter_keywords_lineEdit")
        self.filter_region_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_region_label.setGeometry(QtCore.QRect(20, 108, 350, 31))
        self.filter_region_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_region_label.setLineWidth(0)
        self.filter_region_label.setObjectName("filter_region_label")
        self.filter_region_comboBox = QtWidgets.QComboBox(parent=self.filter_window_frame)
        self.filter_region_comboBox.setGeometry(QtCore.QRect(20, 140, 461, 45))
        self.filter_region_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filter_region_comboBox.setObjectName("filter_region_comboBox")
        self.filter_city_comboBox = QtWidgets.QComboBox(parent=self.filter_window_frame)
        self.filter_city_comboBox.setGeometry(QtCore.QRect(20, 230, 461, 45))
        self.filter_city_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filter_city_comboBox.setObjectName("filter_city_comboBox")
        self.filter_grnti2_lineEdit = QtWidgets.QLineEdit(parent=self.filter_window_frame)
        self.filter_grnti2_lineEdit.setGeometry(QtCore.QRect(270, 320, 211, 45))
        self.filter_grnti2_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_grnti2_lineEdit.setObjectName("filter_grnti2_lineEdit")
        self.filter_grnti2_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_grnti2_label.setGeometry(QtCore.QRect(270, 280, 211, 45))
        self.filter_grnti2_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_grnti2_label.setLineWidth(0)
        self.filter_grnti2_label.setObjectName("filter_grnti2_label")
        self.filter_or_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_or_label.setGeometry(QtCore.QRect(230, 320, 41, 45))
        self.filter_or_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_or_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filter_or_label.setObjectName("filter_or_label")
        self.filter_takepart_label = QtWidgets.QLabel(parent=self.filter_window_frame)
        self.filter_takepart_label.setGeometry(QtCore.QRect(20, 480, 211, 45))
        self.filter_takepart_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.filter_takepart_label.setLineWidth(0)
        self.filter_takepart_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.filter_takepart_label.setObjectName("filter_takepart_label")
        self.filter_takepart_comboBox = QtWidgets.QComboBox(parent=self.filter_window_frame)
        self.filter_takepart_comboBox.setGeometry(QtCore.QRect(260, 480, 211, 45))
        self.filter_takepart_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filter_takepart_comboBox.setObjectName("filter_takepart_comboBox")
        self.filter_apply_button = QtWidgets.QPushButton(parent=self.filter_widget)
        self.filter_apply_button.setGeometry(QtCore.QRect(20, 640, 230, 51))
        self.filter_apply_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_apply_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_apply_button.setObjectName("filter_apply_button")
        self.filter_reset_button = QtWidgets.QPushButton(parent=self.filter_widget)
        self.filter_reset_button.setGeometry(QtCore.QRect(290, 640, 230, 51))
        self.filter_reset_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_reset_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_reset_button.setObjectName("filter_reset_button")
        self.filter_frame = QtWidgets.QFrame(parent=self.filter_widget)
        self.filter_frame.setGeometry(QtCore.QRect(20, 10, 501, 51))
        self.filter_frame.setStyleSheet("")
        self.filter_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.filter_title = QtWidgets.QLabel(parent=self.filter_frame)
        self.filter_title.setGeometry(QtCore.QRect(10, 7, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.filter_title.setFont(font)
        self.filter_title.setStyleSheet("border: none;\n"
"font: 75 14pt \"Segoe UI\";")
        self.filter_title.setLineWidth(0)
        self.filter_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filter_title.setObjectName("filter_title")
        self.filter_close_button = QtWidgets.QPushButton(parent=self.filter_frame)
        self.filter_close_button.setGeometry(QtCore.QRect(420, 0, 81, 51))
        self.filter_close_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_close_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_close_button.setObjectName("filter_close_button")
        self.add_widget = QtWidgets.QWidget(parent=self.page_1)
        self.add_widget.setGeometry(QtCore.QRect(1260, 160, 231, 301))
        self.add_widget.setStyleSheet("")
        self.add_widget.setObjectName("add_widget")
        self.edit_button = QtWidgets.QPushButton(parent=self.add_widget)
        self.edit_button.setGeometry(QtCore.QRect(20, 20, 191, 81))
        self.edit_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_button.setObjectName("edit_button")
        self.add_button = QtWidgets.QPushButton(parent=self.add_widget)
        self.add_button.setGeometry(QtCore.QRect(20, 110, 191, 81))
        self.add_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(parent=self.add_widget)
        self.delete_button.setGeometry(QtCore.QRect(20, 200, 191, 81))
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.delete_button.setObjectName("delete_button")
        self.ramka1 = QtWidgets.QWidget(parent=self.page_1)
        self.ramka1.setGeometry(QtCore.QRect(1260, 480, 231, 121))
        self.ramka1.setStyleSheet("")
        self.ramka1.setObjectName("ramka1")
        self.add_expert_button = QtWidgets.QPushButton(parent=self.ramka1)
        self.add_expert_button.setGeometry(QtCore.QRect(20, 20, 191, 81))
        self.add_expert_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_expert_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.add_expert_button.setObjectName("add_expert_button")
        self.ramka2 = QtWidgets.QWidget(parent=self.page_1)
        self.ramka2.setGeometry(QtCore.QRect(1260, 620, 231, 121))
        self.ramka2.setStyleSheet("")
        self.ramka2.setObjectName("ramka2")
        self.filter_button = QtWidgets.QPushButton(parent=self.ramka2)
        self.filter_button.setGeometry(QtCore.QRect(20, 20, 191, 81))
        self.filter_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_button.setObjectName("filter_button")
        self.init_table = QtWidgets.QTableView(parent=self.page_1)
        self.init_table.setGeometry(QtCore.QRect(25, 80, 1211, 661))
        self.init_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.init_table.setObjectName("init_table")
        self.edit_widget = QtWidgets.QWidget(parent=self.page_1)
        self.edit_widget.setGeometry(QtCore.QRect(980, 0, 541, 720))
        self.edit_widget.setAutoFillBackground(False)
        self.edit_widget.setStyleSheet("")
        self.edit_widget.setObjectName("edit_widget")
        self.edit_window_frame = QtWidgets.QFrame(parent=self.edit_widget)
        self.edit_window_frame.setGeometry(QtCore.QRect(20, 69, 501, 511))
        self.edit_window_frame.setStyleSheet("")
        self.edit_window_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.edit_window_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.edit_window_frame.setObjectName("edit_window_frame")
        self.edit_reg_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_reg_label.setGeometry(QtCore.QRect(20, 100, 469, 45))
        self.edit_reg_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_reg_label.setLineWidth(0)
        self.edit_reg_label.setObjectName("edit_reg_label")
        self.edit_region_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_region_label.setGeometry(QtCore.QRect(20, 200, 211, 31))
        self.edit_region_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_region_label.setLineWidth(0)
        self.edit_region_label.setObjectName("edit_region_label")
        self.edit_grnti_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_grnti_label.setGeometry(QtCore.QRect(20, 290, 211, 31))
        self.edit_grnti_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_grnti_label.setLineWidth(0)
        self.edit_grnti_label.setObjectName("edit_grnti_label")
        self.edit_keyword_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_keyword_label.setGeometry(QtCore.QRect(20, 380, 469, 45))
        self.edit_keyword_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_keyword_label.setLineWidth(0)
        self.edit_keyword_label.setObjectName("edit_keyword_label")
        self.edit_reg_comboBox = QtWidgets.QComboBox(parent=self.edit_window_frame)
        self.edit_reg_comboBox.setGeometry(QtCore.QRect(20, 150, 469, 45))
        self.edit_reg_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_reg_comboBox.setObjectName("edit_reg_comboBox")
        self.edit_grnti_lineEdit = QtWidgets.QLineEdit(parent=self.edit_window_frame)
        self.edit_grnti_lineEdit.setGeometry(QtCore.QRect(20, 330, 211, 45))
        self.edit_grnti_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_grnti_lineEdit.setObjectName("edit_grnti_lineEdit")
        self.edit_keywords_lineEdit = QtWidgets.QLineEdit(parent=self.edit_window_frame)
        self.edit_keywords_lineEdit.setGeometry(QtCore.QRect(20, 430, 469, 45))
        self.edit_keywords_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_keywords_lineEdit.setObjectName("edit_keywords_lineEdit")
        self.edit_name_lineEdit = QtWidgets.QLineEdit(parent=self.edit_window_frame)
        self.edit_name_lineEdit.setGeometry(QtCore.QRect(20, 50, 469, 45))
        self.edit_name_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_name_lineEdit.setObjectName("edit_name_lineEdit")
        self.edit_name_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_name_label.setGeometry(QtCore.QRect(20, 10, 469, 31))
        self.edit_name_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_name_label.setObjectName("edit_name_label")
        self.edit_region_comboBox = QtWidgets.QComboBox(parent=self.edit_window_frame)
        self.edit_region_comboBox.setGeometry(QtCore.QRect(20, 240, 213, 45))
        self.edit_region_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_region_comboBox.setObjectName("edit_region_comboBox")
        self.edit_city_comboBox = QtWidgets.QComboBox(parent=self.edit_window_frame)
        self.edit_city_comboBox.setGeometry(QtCore.QRect(270, 240, 211, 45))
        self.edit_city_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_city_comboBox.setObjectName("edit_city_comboBox")
        self.edit_grnti2_lineEdit = QtWidgets.QLineEdit(parent=self.edit_window_frame)
        self.edit_grnti2_lineEdit.setGeometry(QtCore.QRect(270, 330, 209, 45))
        self.edit_grnti2_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_grnti2_lineEdit.setObjectName("edit_grnti2_lineEdit")
        self.edit_grnti2_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_grnti2_label.setGeometry(QtCore.QRect(270, 290, 211, 31))
        self.edit_grnti2_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_grnti2_label.setLineWidth(0)
        self.edit_grnti2_label.setObjectName("edit_grnti2_label")
        self.edit_city_label = QtWidgets.QLabel(parent=self.edit_window_frame)
        self.edit_city_label.setGeometry(QtCore.QRect(270, 200, 211, 31))
        self.edit_city_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.edit_city_label.setLineWidth(0)
        self.edit_city_label.setObjectName("edit_city_label")
        self.edit_apply_button = QtWidgets.QPushButton(parent=self.edit_widget)
        self.edit_apply_button.setGeometry(QtCore.QRect(20, 600, 231, 51))
        self.edit_apply_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_apply_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_apply_button.setObjectName("edit_apply_button")
        self.edit_frame = QtWidgets.QFrame(parent=self.edit_widget)
        self.edit_frame.setGeometry(QtCore.QRect(20, 10, 501, 51))
        self.edit_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.edit_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.edit_frame.setObjectName("edit_frame")
        self.edit_title = QtWidgets.QLabel(parent=self.edit_frame)
        self.edit_title.setGeometry(QtCore.QRect(20, 10, 461, 31))
        self.edit_title.setStyleSheet("border: none;\n"
"font: 75 14pt \"Segoe UI\";")
        self.edit_title.setLineWidth(0)
        self.edit_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edit_title.setObjectName("edit_title")
        self.edit_close_button = QtWidgets.QPushButton(parent=self.edit_frame)
        self.edit_close_button.setGeometry(QtCore.QRect(420, 0, 81, 51))
        self.edit_close_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_close_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_close_button.setObjectName("edit_close_button")
        self.edit_reset_button = QtWidgets.QPushButton(parent=self.edit_widget)
        self.edit_reset_button.setGeometry(QtCore.QRect(290, 600, 231, 51))
        self.edit_reset_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_reset_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.edit_reset_button.setObjectName("edit_reset_button")
        self.warning_editwidget_label = QtWidgets.QLabel(parent=self.edit_widget)
        self.warning_editwidget_label.setGeometry(QtCore.QRect(20, 660, 501, 41))
        self.warning_editwidget_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.warning_editwidget_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_editwidget_label.setObjectName("warning_editwidget_label")
        self.addexpert_widget = QtWidgets.QWidget(parent=self.page_1)
        self.addexpert_widget.setGeometry(QtCore.QRect(980, 0, 541, 761))
        self.addexpert_widget.setAutoFillBackground(False)
        self.addexpert_widget.setStyleSheet("")
        self.addexpert_widget.setObjectName("addexpert_widget")
        self.addexpert_window = QtWidgets.QFrame(parent=self.addexpert_widget)
        self.addexpert_window.setGeometry(QtCore.QRect(20, 69, 501, 561))
        self.addexpert_window.setStyleSheet("")
        self.addexpert_window.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.addexpert_window.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.addexpert_window.setObjectName("addexpert_window")
        self.addexpert_reg_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_reg_label.setGeometry(QtCore.QRect(20, 100, 461, 45))
        self.addexpert_reg_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_reg_label.setLineWidth(0)
        self.addexpert_reg_label.setObjectName("addexpert_reg_label")
        self.addexpert_city_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_city_label.setGeometry(QtCore.QRect(270, 190, 211, 45))
        self.addexpert_city_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_city_label.setLineWidth(0)
        self.addexpert_city_label.setObjectName("addexpert_city_label")
        self.addexpert_grnti_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_grnti_label.setGeometry(QtCore.QRect(20, 290, 211, 30))
        self.addexpert_grnti_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_grnti_label.setLineWidth(0)
        self.addexpert_grnti_label.setObjectName("addexpert_grnti_label")
        self.addexpert_keyword_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_keyword_label.setGeometry(QtCore.QRect(20, 370, 461, 45))
        self.addexpert_keyword_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_keyword_label.setLineWidth(0)
        self.addexpert_keyword_label.setObjectName("addexpert_keyword_label")
        self.addexpert_reg_comboBox = QtWidgets.QComboBox(parent=self.addexpert_window)
        self.addexpert_reg_comboBox.setGeometry(QtCore.QRect(20, 140, 461, 55))
        self.addexpert_reg_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addexpert_reg_comboBox.setObjectName("addexpert_reg_comboBox")
        self.addexpert_grnti_lineEdit = QtWidgets.QLineEdit(parent=self.addexpert_window)
        self.addexpert_grnti_lineEdit.setGeometry(QtCore.QRect(20, 320, 210, 55))
        self.addexpert_grnti_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.addexpert_grnti_lineEdit.setObjectName("addexpert_grnti_lineEdit")
        self.addexpert_keywords_lineEdit = QtWidgets.QLineEdit(parent=self.addexpert_window)
        self.addexpert_keywords_lineEdit.setGeometry(QtCore.QRect(20, 410, 461, 55))
        self.addexpert_keywords_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.addexpert_keywords_lineEdit.setObjectName("addexpert_keywords_lineEdit")
        self.addexpert_name_lineEdit = QtWidgets.QLineEdit(parent=self.addexpert_window)
        self.addexpert_name_lineEdit.setGeometry(QtCore.QRect(20, 40, 461, 55))
        self.addexpert_name_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.addexpert_name_lineEdit.setObjectName("addexpert_name_lineEdit")
        self.addexpert_name_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_name_label.setGeometry(QtCore.QRect(20, 10, 461, 21))
        self.addexpert_name_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_name_label.setObjectName("addexpert_name_label")
        self.addexpert_grnti2_lineEdit = QtWidgets.QLineEdit(parent=self.addexpert_window)
        self.addexpert_grnti2_lineEdit.setGeometry(QtCore.QRect(270, 320, 210, 55))
        self.addexpert_grnti2_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.addexpert_grnti2_lineEdit.setObjectName("addexpert_grnti2_lineEdit")
        self.addexpert_grnti2_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_grnti2_label.setGeometry(QtCore.QRect(270, 290, 211, 30))
        self.addexpert_grnti2_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_grnti2_label.setObjectName("addexpert_grnti2_label")
        self.addexpert_region_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_region_label.setGeometry(QtCore.QRect(20, 200, 211, 21))
        self.addexpert_region_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";\n"
"")
        self.addexpert_region_label.setObjectName("addexpert_region_label")
        self.addexpert_city_comboBox = QtWidgets.QComboBox(parent=self.addexpert_window)
        self.addexpert_city_comboBox.setGeometry(QtCore.QRect(270, 230, 211, 55))
        self.addexpert_city_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addexpert_city_comboBox.setObjectName("addexpert_city_comboBox")
        self.addexpert_region_comboBox = QtWidgets.QComboBox(parent=self.addexpert_window)
        self.addexpert_region_comboBox.setGeometry(QtCore.QRect(20, 230, 211, 55))
        self.addexpert_region_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addexpert_region_comboBox.setObjectName("addexpert_region_comboBox")
        self.addexpert_takepart_label = QtWidgets.QLabel(parent=self.addexpert_window)
        self.addexpert_takepart_label.setGeometry(QtCore.QRect(20, 490, 211, 55))
        self.addexpert_takepart_label.setStyleSheet("border: none;\n"
"font: 12pt \"Segoe UI\";")
        self.addexpert_takepart_label.setLineWidth(0)
        self.addexpert_takepart_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.addexpert_takepart_label.setObjectName("addexpert_takepart_label")
        self.addexpert_takepart_comboBox = QtWidgets.QComboBox(parent=self.addexpert_window)
        self.addexpert_takepart_comboBox.setGeometry(QtCore.QRect(270, 490, 211, 55))
        self.addexpert_takepart_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addexpert_takepart_comboBox.setObjectName("addexpert_takepart_comboBox")
        self.addexpert_apply_button = QtWidgets.QPushButton(parent=self.addexpert_widget)
        self.addexpert_apply_button.setGeometry(QtCore.QRect(20, 640, 230, 51))
        self.addexpert_apply_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addexpert_apply_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.addexpert_apply_button.setObjectName("addexpert_apply_button")
        self.addexpert_title_frame = QtWidgets.QFrame(parent=self.addexpert_widget)
        self.addexpert_title_frame.setGeometry(QtCore.QRect(20, 10, 501, 51))
        self.addexpert_title_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.addexpert_title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.addexpert_title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.addexpert_title_frame.setObjectName("addexpert_title_frame")
        self.addexpert_title = QtWidgets.QLabel(parent=self.addexpert_title_frame)
        self.addexpert_title.setGeometry(QtCore.QRect(19, 10, 421, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addexpert_title.sizePolicy().hasHeightForWidth())
        self.addexpert_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.addexpert_title.setFont(font)
        self.addexpert_title.setStyleSheet("border: none;\n"
"font: 75 14pt \"Bahnschrift\";")
        self.addexpert_title.setLineWidth(0)
        self.addexpert_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.addexpert_title.setObjectName("addexpert_title")
        self.addexpert_close_button = QtWidgets.QPushButton(parent=self.addexpert_title_frame)
        self.addexpert_close_button.setGeometry(QtCore.QRect(420, 0, 81, 51))
        self.addexpert_close_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addexpert_close_button.setObjectName("addexpert_close_button")
        self.warning_addexpert_label = QtWidgets.QLabel(parent=self.addexpert_widget)
        self.warning_addexpert_label.setGeometry(QtCore.QRect(20, 705, 501, 41))
        self.warning_addexpert_label.setStyleSheet("")
        self.warning_addexpert_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_addexpert_label.setObjectName("warning_addexpert_label")
        self.addexpert_reset_button = QtWidgets.QPushButton(parent=self.addexpert_widget)
        self.addexpert_reset_button.setGeometry(QtCore.QRect(290, 640, 230, 51))
        self.addexpert_reset_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addexpert_reset_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.addexpert_reset_button.setObjectName("addexpert_reset_button")
        self.warning_edit_label = QtWidgets.QLabel(parent=self.page_1)
        self.warning_edit_label.setGeometry(QtCore.QRect(440, 20, 501, 45))
        self.warning_edit_label.setStyleSheet("")
        self.warning_edit_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_edit_label.setObjectName("warning_edit_label")
        self.warning_delete_label = QtWidgets.QLabel(parent=self.page_1)
        self.warning_delete_label.setGeometry(QtCore.QRect(440, 20, 501, 45))
        self.warning_delete_label.setStyleSheet("")
        self.warning_delete_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_delete_label.setObjectName("warning_delete_label")
        self.namberlines_name = QtWidgets.QLabel(parent=self.page_1)
        self.namberlines_name.setGeometry(QtCore.QRect(310, 20, 181, 45))
        self.namberlines_name.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.namberlines_name.setObjectName("namberlines_name")
        self.filterlist_name = QtWidgets.QLabel(parent=self.page_1)
        self.filterlist_name.setGeometry(QtCore.QRect(505, 20, 731, 45))
        self.filterlist_name.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;")
        self.filterlist_name.setObjectName("filterlist_name")
        self.ramka3 = QtWidgets.QWidget(parent=self.page_1)
        self.ramka3.setGeometry(QtCore.QRect(1260, 20, 231, 121))
        self.ramka3.setStyleSheet("")
        self.ramka3.setObjectName("ramka3")
        self.filter_button_2 = QtWidgets.QPushButton(parent=self.ramka3)
        self.filter_button_2.setGeometry(QtCore.QRect(18, 20, 91, 81))
        self.filter_button_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_button_2.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_button_2.setObjectName("filter_button_2")
        self.filter_button_3 = QtWidgets.QPushButton(parent=self.ramka3)
        self.filter_button_3.setGeometry(QtCore.QRect(122, 20, 91, 81))
        self.filter_button_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.filter_button_3.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;")
        self.filter_button_3.setObjectName("filter_button_3")
        self.stackedWidget.addWidget(self.page_1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.work_table = QtWidgets.QTableView(parent=self.page)
        self.work_table.setGeometry(QtCore.QRect(25, 69, 1071, 751))
        self.work_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.work_table.setObjectName("work_table")
        self.table_name_label = QtWidgets.QLabel(parent=self.page)
        self.table_name_label.setGeometry(QtCore.QRect(25, 0, 270, 45))
        self.table_name_label.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.table_name_label.setObjectName("table_name_label")
        self.check_table = QtWidgets.QTableWidget(parent=self.page)
        self.check_table.setGeometry(QtCore.QRect(1090, 69, 101, 751))
        self.check_table.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.check_table.setObjectName("check_table")
        self.check_table.setColumnCount(0)
        self.check_table.setRowCount(0)
        self.ramka = QtWidgets.QWidget(parent=self.page)
        self.ramka.setGeometry(QtCore.QRect(1220, 90, 271, 121))
        self.ramka.setStyleSheet("")
        self.ramka.setObjectName("ramka")
        self.edit_group_button = QtWidgets.QPushButton(parent=self.ramka)
        self.edit_group_button.setGeometry(QtCore.QRect(20, 20, 231, 81))
        self.edit_group_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.edit_group_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;\n"
"")
        self.edit_group_button.setObjectName("edit_group_button")
        self.ramka_2 = QtWidgets.QWidget(parent=self.page)
        self.ramka_2.setGeometry(QtCore.QRect(1220, 250, 271, 121))
        self.ramka_2.setStyleSheet("")
        self.ramka_2.setObjectName("ramka_2")
        self.add_group_button = QtWidgets.QPushButton(parent=self.ramka_2)
        self.add_group_button.setGeometry(QtCore.QRect(20, 20, 231, 81))
        self.add_group_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.add_group_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;\n"
"")
        self.add_group_button.setObjectName("add_group_button")
        self.ramka_3 = QtWidgets.QWidget(parent=self.page)
        self.ramka_3.setGeometry(QtCore.QRect(1220, 410, 271, 121))
        self.ramka_3.setStyleSheet("")
        self.ramka_3.setObjectName("ramka_3")
        self.approve_group_button = QtWidgets.QPushButton(parent=self.ramka_3)
        self.approve_group_button.setGeometry(QtCore.QRect(20, 20, 231, 81))
        self.approve_group_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.approve_group_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;\n"
"")
        self.approve_group_button.setObjectName("approve_group_button")
        self.ramka_4 = QtWidgets.QWidget(parent=self.page)
        self.ramka_4.setGeometry(QtCore.QRect(1220, 570, 271, 121))
        self.ramka_4.setStyleSheet("")
        self.ramka_4.setObjectName("ramka_4")
        self.importExcel_group_button = QtWidgets.QPushButton(parent=self.ramka_4)
        self.importExcel_group_button.setGeometry(QtCore.QRect(20, 20, 231, 81))
        self.importExcel_group_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.importExcel_group_button.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(220, 220, 220);\n"
"border-radius: 7px;\n"
"height: 35px;\n"
"")
        self.importExcel_group_button.setObjectName("importExcel_group_button")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1558, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_show_table = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.menu_show_table.setFont(font)
        self.menu_show_table.setMouseTracking(True)
        self.menu_show_table.setObjectName("menu_show_table")
        self.menu_work_group = QtWidgets.QMenu(parent=self.menubar)
        self.menu_work_group.setObjectName("menu_work_group")
        self.menu_help = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.menu_help.setFont(font)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.ntp_show = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.ntp_show.setFont(font)
        self.ntp_show.setObjectName("ntp_show")
        self.grnti_show = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grnti_show.setFont(font)
        self.grnti_show.setObjectName("grnti_show")
        self.reg_show = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reg_show.setFont(font)
        self.reg_show.setObjectName("reg_show")
        self.load_group = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.load_group.setFont(font)
        self.load_group.setObjectName("load_group")
        self.save_group = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_group.setFont(font)
        self.save_group.setObjectName("save_group")
        self.delete_group = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_group.setFont(font)
        self.delete_group.setObjectName("delete_group")
        self.hotkeys_show = QtGui.QAction(parent=MainWindow)
        self.hotkeys_show.setObjectName("hotkeys_show")
        self.recover = QtGui.QAction(parent=MainWindow)
        self.recover.setObjectName("recover")
        self.menu_show_table.addAction(self.ntp_show)
        self.menu_show_table.addAction(self.reg_show)
        self.menu_show_table.addAction(self.grnti_show)
        self.menu_work_group.addAction(self.load_group)
        self.menu_work_group.addAction(self.save_group)
        self.menu_work_group.addAction(self.delete_group)
        self.menu_help.addAction(self.hotkeys_show)
        self.menu_help.addAction(self.recover)
        self.menubar.addAction(self.menu_show_table.menuAction())
        self.menubar.addAction(self.menu_work_group.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление организацией экспертизы научно-технических проектов."))
        self.text_label_3.setText(_translate("MainWindow", "Отображение таблицы НТП (\'Ctrl+1\')\n"
"Отображение справочника по регионам (\'Ctrl+2\')\n"
"Отображение справочника по ГРНТИ (\'Ctrl+3\')\n"
"Удалить строку (\'backspace\')\n"
"Открыть фильтр (\'f\')\n"
"Закрыть виджет(\'escape\')"))
        self.label_3.setText(_translate("MainWindow", "Горячие клавиши"))
        self.help_close_button_3.setText(_translate("MainWindow", "Закрыть"))
        self.init_tablename.setText(_translate("MainWindow", "  Эксперты НТП"))
        self.filter_reg_label.setText(_translate("MainWindow", "Федеральный округ"))
        self.filter_city_label.setText(_translate("MainWindow", "Город"))
        self.filter_grnti_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.filter_keyword_label.setText(_translate("MainWindow", "Ключевые слова"))
        self.filter_region_label.setText(_translate("MainWindow", "Регион"))
        self.filter_grnti2_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.filter_or_label.setText(_translate("MainWindow", "или"))
        self.filter_takepart_label.setText(_translate("MainWindow", "Участие в экспертизах "))
        self.filter_apply_button.setText(_translate("MainWindow", "применить"))
        self.filter_reset_button.setText(_translate("MainWindow", "сбросить"))
        self.filter_title.setText(_translate("MainWindow", "Фильтр"))
        self.filter_close_button.setText(_translate("MainWindow", "Закрыть"))
        self.edit_button.setText(_translate("MainWindow", "Редактировать"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.delete_button.setText(_translate("MainWindow", "Удалить"))
        self.add_expert_button.setText(_translate("MainWindow", "Создать эскпертную \n"
"группу"))
        self.filter_button.setText(_translate("MainWindow", "Фильтр"))
        self.edit_reg_label.setText(_translate("MainWindow", "Федеральный округ"))
        self.edit_region_label.setText(_translate("MainWindow", "Регион"))
        self.edit_grnti_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.edit_keyword_label.setText(_translate("MainWindow", "Ключевые слова"))
        self.edit_name_label.setText(_translate("MainWindow", "ФИО"))
        self.edit_grnti2_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.edit_city_label.setText(_translate("MainWindow", "Город"))
        self.edit_apply_button.setText(_translate("MainWindow", "применить"))
        self.edit_title.setText(_translate("MainWindow", "Изменение"))
        self.edit_close_button.setText(_translate("MainWindow", "Закрыть"))
        self.edit_reset_button.setText(_translate("MainWindow", "сбросить"))
        self.warning_editwidget_label.setText(_translate("MainWindow", "Такой эксперт уже добавлен!"))
        self.addexpert_reg_label.setText(_translate("MainWindow", "Федеральный округ"))
        self.addexpert_city_label.setText(_translate("MainWindow", "Город"))
        self.addexpert_grnti_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.addexpert_keyword_label.setText(_translate("MainWindow", "Ключевые слова"))
        self.addexpert_name_label.setText(_translate("MainWindow", "ФИО"))
        self.addexpert_grnti2_label.setText(_translate("MainWindow", "ГРНТИ"))
        self.addexpert_region_label.setText(_translate("MainWindow", "Регион"))
        self.addexpert_takepart_label.setText(_translate("MainWindow", "Участие в экспертизах "))
        self.addexpert_apply_button.setText(_translate("MainWindow", "применить"))
        self.addexpert_title.setText(_translate("MainWindow", "Добавление"))
        self.addexpert_close_button.setText(_translate("MainWindow", "Закрыть"))
        self.warning_addexpert_label.setText(_translate("MainWindow", "Такой эксперт уже добавлен"))
        self.addexpert_reset_button.setText(_translate("MainWindow", "сбросить"))
        self.warning_edit_label.setText(_translate("MainWindow", "Редактировать можно только одну строку!"))
        self.warning_delete_label.setText(_translate("MainWindow", "Нет выделенных строк!"))
        self.namberlines_name.setText(_translate("MainWindow", "  Число строк:"))
        self.filterlist_name.setText(_translate("MainWindow", "  Фильтр:"))
        self.filter_button_2.setText(_translate("MainWindow", "Выделить\n"
"всё"))
        self.filter_button_3.setText(_translate("MainWindow", "Убрать\n"
"выделение"))
        self.table_name_label.setText(_translate("MainWindow", "Экспертная группа"))
        self.edit_group_button.setText(_translate("MainWindow", "Исключить экспертов"))
        self.add_group_button.setText(_translate("MainWindow", "Добавить \n"
"ещё одну \n"
"группу"))
        self.approve_group_button.setText(_translate("MainWindow", "Утвердить группу"))
        self.importExcel_group_button.setText(_translate("MainWindow", "Импортировать в Excel"))
        self.menu_show_table.setTitle(_translate("MainWindow", "Данные"))
        self.menu_work_group.setTitle(_translate("MainWindow", "Работа с экспертными группами"))
        self.menu_help.setTitle(_translate("MainWindow", "Инструменты"))
        self.ntp_show.setText(_translate("MainWindow", "Эксперты НТП"))
        self.grnti_show.setText(_translate("MainWindow", "Код рубрики (ГРНТИ)"))
        self.reg_show.setText(_translate("MainWindow", "Справочник по регионам "))
        self.load_group.setText(_translate("MainWindow", "Загрузить группу"))
        self.save_group.setText(_translate("MainWindow", "Сохранить группу"))
        self.delete_group.setText(_translate("MainWindow", "Удалить группу"))
        self.hotkeys_show.setText(_translate("MainWindow", "Горячие клавиши"))
        self.recover.setText(_translate("MainWindow", "Восстановление базы данных"))
